# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('original_acl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_name', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=20)),
                ('interface', models.CharField(max_length=100)),
                ('original_acl', models.CharField(max_length=255)),
                ('line_no', models.PositiveIntegerField()),
                ('has_objectgroup', models.BooleanField()),
                ('src_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('src_mask', models.CharField(max_length=100)),
                ('src_port_low', models.PositiveIntegerField(default=0)),
                ('src_port_high', models.PositiveIntegerField(default=65535)),
                ('dst_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('dst_mask', models.CharField(max_length=100)),
                ('dst_port_low', models.PositiveIntegerField(default=0)),
                ('dst_port_high', models.PositiveIntegerField(default=65535)),
                ('action', models.CharField(max_length=20)),
                ('time_range', models.DateField()),
                ('hitcnt', models.PositiveIntegerField(default=0)),
                ('uuid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('end_datetime', models.DateTimeField()),
                ('firewall_name', models.CharField(max_length=50)),
            ],
        ),
    ]
