# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packetTracert', '0003_auto_20181109_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_group', models.CharField(max_length=50)),
                ('interface', models.CharField(max_length=50)),
                ('firewall_name', models.CharField(max_length=50)),
            ],
        ),
    ]
