# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FWAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputer', models.CharField(max_length=50)),
                ('firewall', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('firemon_original', models.TextField(blank=True)),
                ('firemon_handle', models.TextField(blank=True)),
                ('firemon_final', models.TextField(blank=True)),
                ('expire', models.CharField(max_length=50)),
                ('exec_time', models.DateTimeField(blank=True)),
                ('order', models.CharField(max_length=50)),
                ('requirement', models.TextField()),
                ('dissidence', models.CharField(max_length=50)),
                ('other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FWResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_matrix_acl', models.IntegerField(default=0)),
                ('rubbish_acl', models.IntegerField(default=0)),
                ('any_acl', models.IntegerField(default=0)),
                ('hight_danger_acl', models.IntegerField(default=0)),
                ('no_registered_acl', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('display_row', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FWTempResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_matrix_acl', models.IntegerField(default=0)),
                ('rubbish_acl', models.IntegerField(default=0)),
                ('any_acl', models.IntegerField(default=0)),
                ('hight_danger_acl', models.IntegerField(default=0)),
                ('no_registered_acl', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('display_row', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FWUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('acs_account', models.CharField(blank=True, max_length=50)),
                ('ad_account', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fwaccount',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firewallAccount.FWUser', verbose_name='username'),
        ),
    ]
